name: CI/CD Pipeline for MemPersist Cache

on:
  push:
    branches:
      - main
      - staging
      - non-prod
  pull_request:
    branches:
      - main
      - staging
      - non-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List All Files for Debugging
        run: |
          echo "Listing all files in root directory:"
          ls -R .
          echo "Listing contents of cache-project directory specifically:"
          ls -R ./cache-project

      - name: Build with Maven
        run: |
          cd cache-project
          mvn -B clean install

      - name: Run Tests with Test Profile and Retry Strategy
        run: |
          cd cache-project
          mvn test -Dspring.profiles.active=test --fail-at-end -X
