name: CI/CD Pipeline for MemPersist Cache

on:
  push:
    branches:
      - main
      - staging
      - non-prod
  pull_request:
    branches:
      - main
      - staging
      - non-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd cache-project
          mvn -B clean install

      - name: Run Tests
        run: |
          cd cache-project
          MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m" mvn -B test
        env:
          SPRING_PROFILES_ACTIVE: test
          TEST_RETRY: 2  # Retries if tests fail
