name: CI/CD Pipeline for MemPersist Cache

on:
  push:
    branches:
      - main
      - staging
      - non-prod
  pull_request:
    branches:
      - main
      - staging
      - non-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Increase JVM Options and Build with Maven
        run: |
          cd cache-project
          MAVEN_OPTS="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError" mvn clean install -DskipTests=false

      - name: Run Tests with Test Profile and Retry Strategy
        run: |
          cd cache-project
          MAVEN_OPTS="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError" mvn test -Dspring.profiles.active=test --fail-at-end
