name: CI/CD Pipeline for MemPersist Cache

on:
  push:
    branches:
      - main
      - staging
      - non-prod
  pull_request:
    branches:
      - main
      - staging
      - non-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List All Files for Debugging
        run: |
          echo "Listing all files in root directory:"
          ls -R .
          echo "Listing contents of cache-project directory specifically:"
          ls -R ./cache-project

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/cache-project/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Change Directory to cache-project
        working-directory: ./cache-project
        run: |
          echo "Now in cache-project directory. Confirming contents:"
          ls

      - name: Build with Maven
        working-directory: ./cache-project
        run: |
          echo "Running Maven Build in cache-project directory..."
          mvn -B clean install

      - name: Run Tests
        working-directory: ./cache-project
        run: |
          echo "Running Maven Tests in cache-project directory..."
          mvn -B test
