name: CI/CD Pipeline for MemPersist Cache

on:
  push:
    branches:
      - main
      - staging
      - non-prod
  pull_request:
    branches:
      - main
      - staging
      - non-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # This is the default OpenJDK distribution

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "env=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "env=staging" >> $GITHUB_ENV
          else
            echo "env=non-prod" >> $GITHUB_ENV
          fi

      - name: Deploy to Server
        run: |
          echo "Deploying to ${{ env.env }} environment..."
          # Add your specific deployment commands here, such as:
          # if [[ "${{ env.env }}" == "production" ]]; then
          #   ssh user@production-server 'deploy-commands'
          # elif [[ "${{ env.env }}" == "staging" ]]; then
          #   ssh user@staging-server 'deploy-commands'
          # else
          #   ssh user@non-prod-server 'deploy-commands'
          # fi
