name: CI/CD Pipeline for MemPersist Cache

on:
  push:
    branches:
      - main
      - staging
      - non-prod
  pull_request:
    branches:
      - main
      - staging
      - non-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List All Files for Debugging
        run: |
          echo "Listing all files in root directory:"
          ls -R .
          echo "Listing contents of cache-project directory specifically:"
          ls -R ./cache-project

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/cache-project/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Confirm Cache Project Pom
        run: |
          if [[ -f "./cache-project/pom.xml" ]]; then
            echo "Found cache-project/pom.xml."
          else
            echo "Error: cache-project/pom.xml does not exist!"
            exit 1
          fi

      - name: Build with Maven
        run: |
          echo "Running Maven Build in cache-project directory..."
          mvn -B -f ./cache-project/pom.xml clean install

      - name: Run Tests
        run: |
          echo "Running Maven Tests in cache-project directory..."
          mvn -B -f ./cache-project/pom.xml test
