name: CI/CD Pipeline for MemPersist Cache

on:
  push:
    branches:
      - main
      - non-prod
      - prod
      - staging
      - test
  pull_request:
    branches:
      - main
      - non-prod
      - prod
      - staging
      - test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: List All Files for Debugging
        run: ls -R .

      - name: Build with Maven
        run: |
          cd cache-project
          mvn -B clean install
        env:
          MAVEN_OPTS: "-Xms512m -Xmx2048m"

      - name: Run Tests with Test Profile
        run: |
          cd cache-project
          mvn test -Dspring.profiles.active=test --fail-at-end
        env:
          MAVEN_OPTS: "-Xms512m -Xmx2048m"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: cache-project/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    strategy:
      matrix:
        env: [test, staging, nonprod, prod]

    if: github.ref == 'refs/heads/${{ matrix.env }}'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Deploy to ${{ matrix.env }} Environment
        run: |
          echo "Deploying to ${{ matrix.env }} environment..."
        env:
          SPRING_PROFILES_ACTIVE: ${{ matrix.env }}
