name: CI/CD Pipeline for MemPersist Cache

on:
  push:
    branches:
      - main
      - staging
      - non-prod
      - prod
      - test
  pull_request:
    branches:
      - main
      - staging
      - non-prod
      - prod
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List All Files for Debugging
        run: |
          echo "Listing all files in the root directory:"
          ls -R .
          echo "Listing contents of cache-project directory specifically:"
          ls -R ./cache-project

      - name: Build with Maven
        run: |
          if [ -d "./cache-project" ]; then
            cd cache-project
            mvn -B clean install
          else
            echo "cache-project directory not found!"
            exit 1
          fi
        env:
          MAVEN_OPTS: "-Xms512m -Xmx2048m"

      - name: Run Tests with Test Profile and Retry Strategy
        run: |
          if [ -d "./cache-project" ]; then
            cd cache-project
            mvn test -Dspring.profiles.active=test --fail-at-end -X
          else
            echo "cache-project directory not found!"
            exit 1
          fi
        env:
          MAVEN_OPTS: "-Xms512m -Xmx2048m"

  deploy-test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Test Environment
        run: |
          echo "Deploying to Test environment..."
          # Add deployment script or commands here for test environment
        env:
          SPRING_PROFILES_ACTIVE: test

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Staging Environment
        run: |
          echo "Deploying to Staging environment..."
          # Add deployment script or commands here for staging
        env:
          SPRING_PROFILES_ACTIVE: staging

  deploy-nonprod:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/non-prod'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Non-Prod Environment
        run: |
          echo "Deploying to Non-Prod environment..."
          # Add deployment script or commands here for non-prod
        env:
          SPRING_PROFILES_ACTIVE: nonprod

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Production Environment
        run: |
          echo "Deploying to Production environment..."
          # Add deployment script or commands here for production
        env:
          SPRING_PROFILES_ACTIVE: prod
