spring:
  datasource:
    url: jdbc:h2:mem:testdb  # Use in-memory database for testing
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: create-drop  # Automatically create and drop tables for each test
  main:
    allow-bean-definition-overriding: true

# Disable monitoring and additional features not required in tests
management:
  endpoints:
    web:
      exposure:
        include: health  # Limit to health endpoint in tests
  endpoint:
    health:
      show-details: always
